name: app4_receitas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_speed_dial: ^7.0.0
  get: ^4.7.2
  get_it: ^8.2.0
  go_router: ^16.0.0
  google_fonts: ^6.3.0
  supabase_flutter: ^2.9.1
  either_dart: ^1.0.0
  intl: 0.20.2
  shared_preferences: ^2.3.2
  # dartz: ^0.10.1
  country_icons: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dwds: ^25.0.2
  mockito: ^5.4.4
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.14.1


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/.env
    - assets/images/

# Configuração do ícone do app
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48