// Mocks generated by Mockito 5.4.6 from annotations
// in app4_receitas/test/ui/auth/auth_view_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i11;

import 'package:app4_receitas/data/models/user_profile.dart' as _i8;
import 'package:app4_receitas/data/repositories/auth_repository.dart' as _i4;
import 'package:app4_receitas/data/services/auth_service.dart' as _i12;
import 'package:app4_receitas/ui/auth/auth_viewmodel.dart' as _i14;
import 'package:app4_receitas/utils/app_error.dart' as _i7;
import 'package:either_dart/either.dart' as _i6;
import 'package:flutter/widgets.dart' as _i3;
import 'package:get/get.dart' as _i2;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:supabase_flutter/supabase_flutter.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInternalFinalCallback_0<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGlobalKey_1<T extends _i3.State<_i3.StatefulWidget>>
    extends _i1.SmartFake
    implements _i3.GlobalKey<T> {
  _FakeGlobalKey_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTextEditingController_2 extends _i1.SmartFake
    implements _i3.TextEditingController {
  _FakeTextEditingController_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Either<_i7.AppError, _i8.UserProfile>> get currentUser =>
      (super.noSuchMethod(
            Invocation.getter(#currentUser),
            returnValue:
                _i5.Future<_i6.Either<_i7.AppError, _i8.UserProfile>>.value(
                  _i9.dummyValue<_i6.Either<_i7.AppError, _i8.UserProfile>>(
                    this,
                    Invocation.getter(#currentUser),
                  ),
                ),
          )
          as _i5.Future<_i6.Either<_i7.AppError, _i8.UserProfile>>);

  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  _i5.Future<_i6.Either<_i7.AppError, _i8.UserProfile>> signInWithPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i5.Future<_i6.Either<_i7.AppError, _i8.UserProfile>>.value(
                  _i9.dummyValue<_i6.Either<_i7.AppError, _i8.UserProfile>>(
                    this,
                    Invocation.method(#signInWithPassword, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i6.Either<_i7.AppError, _i8.UserProfile>>);

  @override
  _i5.Future<_i6.Either<_i7.AppError, _i8.UserProfile>> signUp({
    required String? email,
    required String? password,
    required String? username,
    required String? avatarUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
              #username: username,
              #avatarUrl: avatarUrl,
            }),
            returnValue:
                _i5.Future<_i6.Either<_i7.AppError, _i8.UserProfile>>.value(
                  _i9.dummyValue<_i6.Either<_i7.AppError, _i8.UserProfile>>(
                    this,
                    Invocation.method(#signUp, [], {
                      #email: email,
                      #password: password,
                      #username: username,
                      #avatarUrl: avatarUrl,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i6.Either<_i7.AppError, _i8.UserProfile>>);

  @override
  _i5.Future<_i6.Either<_i7.AppError, void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<_i6.Either<_i7.AppError, void>>.value(
              _i9.dummyValue<_i6.Either<_i7.AppError, void>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.AppError, void>>);

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Disposer addListener(_i10.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i10.Disposer);

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i11.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Disposer addListenerId(Object? key, _i10.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i10.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i12.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i13.AuthState> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i5.Stream<_i13.AuthState>.empty(),
          )
          as _i5.Stream<_i13.AuthState>);

  @override
  _i5.Future<_i6.Either<_i7.AppError, _i13.AuthResponse>> signInWithPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i5.Future<_i6.Either<_i7.AppError, _i13.AuthResponse>>.value(
                  _i9.dummyValue<_i6.Either<_i7.AppError, _i13.AuthResponse>>(
                    this,
                    Invocation.method(#signInWithPassword, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i6.Either<_i7.AppError, _i13.AuthResponse>>);

  @override
  _i5.Future<_i6.Either<_i7.AppError, Map<String, dynamic>?>> fetchUserProfile(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserProfile, [userId]),
            returnValue:
                _i5.Future<
                  _i6.Either<_i7.AppError, Map<String, dynamic>?>
                >.value(
                  _i9.dummyValue<
                    _i6.Either<_i7.AppError, Map<String, dynamic>?>
                  >(this, Invocation.method(#fetchUserProfile, [userId])),
                ),
          )
          as _i5.Future<_i6.Either<_i7.AppError, Map<String, dynamic>?>>);

  @override
  _i5.Future<_i6.Either<_i7.AppError, _i13.AuthResponse>> signUp({
    required String? email,
    required String? password,
    required String? username,
    required String? avatarUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
              #username: username,
              #avatarUrl: avatarUrl,
            }),
            returnValue:
                _i5.Future<_i6.Either<_i7.AppError, _i13.AuthResponse>>.value(
                  _i9.dummyValue<_i6.Either<_i7.AppError, _i13.AuthResponse>>(
                    this,
                    Invocation.method(#signUp, [], {
                      #email: email,
                      #password: password,
                      #username: username,
                      #avatarUrl: avatarUrl,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i6.Either<_i7.AppError, _i13.AuthResponse>>);

  @override
  _i5.Future<_i6.Either<_i7.AppError, _i13.AuthResponse>> insertUser({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertUser, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i5.Future<_i6.Either<_i7.AppError, _i13.AuthResponse>>.value(
                  _i9.dummyValue<_i6.Either<_i7.AppError, _i13.AuthResponse>>(
                    this,
                    Invocation.method(#insertUser, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i6.Either<_i7.AppError, _i13.AuthResponse>>);

  @override
  _i5.Future<_i6.Either<_i7.AppError, void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<_i6.Either<_i7.AppError, void>>.value(
              _i9.dummyValue<_i6.Either<_i7.AppError, void>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i5.Future<_i6.Either<_i7.AppError, void>>);
}

/// A class which mocks [AuthViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthViewModel extends _i1.Mock implements _i14.AuthViewModel {
  MockAuthViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GlobalKey<_i3.FormState> get formKey =>
      (super.noSuchMethod(
            Invocation.getter(#formKey),
            returnValue: _FakeGlobalKey_1<_i3.FormState>(
              this,
              Invocation.getter(#formKey),
            ),
          )
          as _i3.GlobalKey<_i3.FormState>);

  @override
  _i3.TextEditingController get emailController =>
      (super.noSuchMethod(
            Invocation.getter(#emailController),
            returnValue: _FakeTextEditingController_2(
              this,
              Invocation.getter(#emailController),
            ),
          )
          as _i3.TextEditingController);

  @override
  _i3.TextEditingController get passwordController =>
      (super.noSuchMethod(
            Invocation.getter(#passwordController),
            returnValue: _FakeTextEditingController_2(
              this,
              Invocation.getter(#passwordController),
            ),
          )
          as _i3.TextEditingController);

  @override
  _i3.TextEditingController get confirmPasswordController =>
      (super.noSuchMethod(
            Invocation.getter(#confirmPasswordController),
            returnValue: _FakeTextEditingController_2(
              this,
              Invocation.getter(#confirmPasswordController),
            ),
          )
          as _i3.TextEditingController);

  @override
  _i3.TextEditingController get usernameController =>
      (super.noSuchMethod(
            Invocation.getter(#usernameController),
            returnValue: _FakeTextEditingController_2(
              this,
              Invocation.getter(#usernameController),
            ),
          )
          as _i3.TextEditingController);

  @override
  _i3.TextEditingController get avatarUrlController =>
      (super.noSuchMethod(
            Invocation.getter(#avatarUrlController),
            returnValue: _FakeTextEditingController_2(
              this,
              Invocation.getter(#avatarUrlController),
            ),
          )
          as _i3.TextEditingController);

  @override
  bool get obscurePassword =>
      (super.noSuchMethod(
            Invocation.getter(#obscurePassword),
            returnValue: false,
          )
          as bool);

  @override
  bool get isSubmitting =>
      (super.noSuchMethod(Invocation.getter(#isSubmitting), returnValue: false)
          as bool);

  @override
  bool get isLoginMode =>
      (super.noSuchMethod(Invocation.getter(#isLoginMode), returnValue: false)
          as bool);

  @override
  String get errorMessage =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessage),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#errorMessage),
            ),
          )
          as String);

  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  void toggleObscurePassword() => super.noSuchMethod(
    Invocation.method(#toggleObscurePassword, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> submit() =>
      (super.noSuchMethod(
            Invocation.method(#submit, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> login() =>
      (super.noSuchMethod(
            Invocation.method(#login, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> register() =>
      (super.noSuchMethod(
            Invocation.method(#register, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void toggleMode() => super.noSuchMethod(
    Invocation.method(#toggleMode, []),
    returnValueForMissingStub: null,
  );

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Disposer addListener(_i10.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i10.Disposer);

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i11.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Disposer addListenerId(Object? key, _i10.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i10.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}
